name: CI
permissions:
  contents: read

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  lint:
    name: Lint and Type Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Setup uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2

      - name: Lint
        run: uv run --frozen pre-commit run --all-files

  test:
    name: Unit Tests - Python ${{ matrix.python-version }}
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12", "3.13", "3.14"]
      fail-fast: false
    steps:
      - name: Checkout code
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Setup uv
        uses: astral-sh/setup-uv@11f9893b081a58869d3b5fccaea48c9e9e46f990 # v8.3.2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run tests for given python version
        run: uv run --frozen pytest --cov=src/epicsdb2bob --cov-report=xml --cov-report=term

      - name: Upload Coverage To Codecov
        if: ${{ matrix.python-version == '3.13' }}
        uses: codecov/codecov-action@v7
        with:
          name: Coverage
          files: coverage.xml
          token: ${{ secrets.CODECOV_TOKEN }}
